- .claude/settings.local.json
- .gitignore
Remove `.claude/settings.local.json` from git tracking and add to .gitignore to prevent future tracking.
- **Remove from git**: Stop tracking `.claude/settings.local.json`
- **.gitignore update**: Add `.claude/settings.local.json` to prevent future commits
- **Local file preserved**: Keep local file for development purposes
- Local settings should not be shared in template repositories
- Users should configure Claude Code permissions individually
- Prevents accidental commit of personal development settings
- Used `git rm --cached` to remove from tracking without deleting local file
- Added specific ignore pattern for Claude Code local settings
- Template users will need to configure their own `.claude/settings.local.json` if needed
This PR is based on the `improve-docker-build-output` …
> Remove .claude/settings.local.json from repository tracking

- create-repo/main-wr.sh
- create-repo/main.sh
- create-repo/setup-wr.sh
- create-repo/setup.sh
テンプレートファイル整理時とLaTeX環境セットアップ時に、git commit の詳細出力が表示されて冗長でした：
```
[main 892c980] Remove graduate thesis template files
2 files changed, 119 deletions(-)
delete mode 100644 abstract.tex
delete mode 100644 thesis.tex
[main 611abab] Add LaTeX development environment with devcontainer  
6 files changed, 341 insertions(+)
create mode 100644 .devcontainer/SETUP-devcontainer.md
...
```
以下のgit commit操作に `>/dev/null 2>&1` を追加：
**main.sh**:
- テンプレートファイル削除時のコミット
- LaTeX環境セットアップ完了時のコミット
**main-wr.sh**:  
- LaTeX環境セットアップ完了時のコミット
```
テンプレートファイルを整理中...
[main abc123] Remove graduate thesis template files
2 files changed, 119 deletions(-)
delete mode 100644 abstract.tex
delete mode 100644 thesis.tex
LaTeX環境をセットアップ中...
✓ LaTeX環境のセットアップ完了
[main def456] Add LaTeX development environment with devcontainer
6 …
```
> Suppress git commit output for cleaner setup experience

- .github/workflows/student-repo-management.yml
- .gitignore
- data/.gitkeep
- scripts/bulk-setup-protection.sh
- scripts/extract-student-info-from-issues.sh
- scripts/test-extract-issues.sh
- scripts/update-student-registry.sh
- Issue駆動での学生レジストリ自動更新システムを実装
- リポジトリ作成日時ベースでの年度判定機能を追加
- GitHub Actionsによる2時間ごとの自動実行ワークフロー
- `.github/workflows/student-repo-management.yml` - 自動化ワークフロー
- `scripts/extract-student-info-from-issues.sh` - Issue情報抽出スクリプト
- `scripts/update-student-registry.sh` - レジストリ更新・保守スクリプト
- `scripts/test-extract-issues.sh` - テストスクリプト
- `scripts/bulk-setup-protection.sh` - リポジトリ名対応、Issue自動クローズ機能追加
- `.gitignore` - レジストリデータファイルを除外
1. **Issue駆動の自動化**
- 「ブランチ保護設定依頼」Issueから学生情報を自動抽出
- 2時間ごとにGitHub Actionsで自動実行
2. **年度判定の改善** 
- 学生IDの入学年度ではなく、リポジトリ作成日時の年度で分類
- ユーザー要望「学生の学年は、id ではなくリポジトリ作成日時の「年」で判断してほしい」に対応
3. **ファイルベースレジストリ**
- 高速な状態確認のためのファイル管理システム
- 年度別・タイプ別の学生分類
4. **自動Issue管理**
- ブランチ保護設定完了時に関連Issueを自動クローズ
- `yamllint`: ✅ すべてのチェックをパス
- `actionlint`: ✅ GitHub Actions固有のエラーなし
- 実行テスト: …
> Implement automated student registry system (Phase 2)

- .github/workflows/ai-reviewer.yml
ai-reviewer.ymlワークフローでサポートされていないパラメータによる警告を修正
Nasubikun/ai-reviewer@v1アクションで`USE_SINGLE_COMMENT_REVIEW`パラメータがサポートされておらず、GitHub Actionsで警告が発生していました：
```
Unexpected input(s) 'USE_SINGLE_COMMENT_REVIEW', valid inputs are ['GEMINI_API_KEY', 'GITHUB_TOKEN', 'MODEL_CODE', 'LANGUAGE', 'EXCLUDE_PATHS']
```
- `USE_SINGLE_COMMENT_REVIEW: "true"`パラメータを削除
- サポートされているパラメータのみ使用
- `GEMINI_API_KEY` ✅
- `GITHUB_TOKEN` ✅  
- `MODEL_CODE` (未使用)
- `LANGUAGE` ✅
- `EXCLUDE_PATHS` ✅
- ✅ GitHub Actions警告の解消
- ✅ ワークフロー実行の正常化
- ✅ 機能への影響なし（レビュー機能は継続して動作）
- `yamllint`: ✅ パス
- `actionlint`: ✅ パス
- GitHub Actions実行ID: 15803889160での警告解消
- 今後のPRでのAIレビュー機能正常化
この修正により、AIレビューワークフローが警告なしで正常に動作するようになります。
> Fix ai-reviewer.yml: Remove unsupported parameter

- .github/workflows/ai-reviewer.yml
- create-repo/main-wr.sh
- create-repo/main.sh
学籍番号入力の柔軟性を向上させ、ユーザビリティを改善しました。
- **先頭k自動追加**: `24rs509` → `k24rs509`
- **大文字→小文字変換**: `24RS509` → `k24rs509`
- **組み合わせ対応**: 大文字・k無しの入力も適切に処理
| 入力例 | 正規化後 | 論文タイプ |
|--------|----------|------------|
| `24rs509` | `k24rs509` | 卒業論文 |
| `24RS509` | `k24rs509` | 卒業論文 |
| `21gjk01` | `k21gjk01` | 修士論文 |
| `21GJK01` | `k21gjk01` | 修士論文 |
- 標準形式のみを例示（`k21rs001`, `k21gjk01`）
- 自動補正機能については明示しない
- 正規化が発生した場合のみ通知
- 例: `✓ 学籍番号を正規化しました: 24rs509 → k24rs509`
- `create-repo/main.sh`: 論文リポジトリ作成用
- `create-repo/main-wr.sh`: 週報リポジトリ作成用
```bash
STUDENT_ID=24rs509 ./main.sh    # k24rs509として処理
STUDENT_ID=24RS509 ./main.sh    # k24rs509として処理
STUDENT_ID=k24rs509 ./main.sh   # そのまま処理
```
- 学生がより柔軟に学籍番号を入力可能
- 入力ミスによるエラーを削減
- 正しい形式を学習する機会を提供
> Add flexible student ID input with auto-normalization

- scripts/extract-student-info-from-issues.sh
• Fixed cleanup_duplicates function causing workflow failures
• Resolved set -e pipefail compatibility issues in GitHub Actions
• Fixed arithmetic operation compatibility with strict mode
1. cleanup_duplicates function using problematic while-read pipeline with set -e
2. ((processed++)) operation failing under strict mode in GitHub Actions
• Replaced `find | while read` with process substitution `< <(find -print0)`
• Changed `((processed++))` to `processed=$((processed + 1))`
• Added explicit error handling for sort operations  
• Used -e flag checks to prevent non-existent file errors
• Added debug logging for better troubleshooting
> Fix cleanup_duplicates function for GitHub Actions compatibility

- scripts/bulk-setup-protection.sh
• Fix workflow failure when no pending repositories exist
• Handle empty or missing pending-protection.txt gracefully
• Exit normally instead of with error when nothing to process
Workflow was failing with:
```
Pending file not found: /home/runner/work/.../data/protection-status/pending-protection.txt
Process completed with exit code 1
```
This happens when:
- All issues have been processed
- No new repositories need protection setup
- The pending file is empty or doesn't exist
• Check if file exists → log and exit 0 (not error)
• Check if file is empty → log and exit 0 
• Fix `((total_count++))` to work with strict mode
• These are normal conditions, not errors
> Fix handling of empty or missing pending-protection.txt file

- scripts/update-student-registry.sh
• Fix workflow failure in Update student registry step
• Replace ((var++)) operations with bash strict mode compatible syntax
• Prevent exit code 1 from arithmetic operations
Workflow failing with:
```
存在しないリポジトリを pending から削除: k18rs910-sotsuron
Process completed with exit code 1
```
Using `((cleaned++))` and similar operations in bash strict mode (`set -e`) causes script termination when the operation would be falsy.
Replace all instances of `((var++))` with `var=$((var + 1))` which is compatible with strict mode.
> Fix arithmetic operations in update-student-registry.sh

- .github/workflows/student-repo-management.yml
- scripts/setup-branch-protection.sh
setup-branch-protection.shでGitHub Actions環境での認証エラーを解決
- **認証チェック改善**: `gh api user` → `gh auth status` に変更
- **環境検出**: `GITHUB_ACTIONS`環境変数でGitHub Actions環境を検出
- **権限チェック最適化**: GitHub Actions環境では権限チェックをスキップ（GITHUB_TOKENで十分な権限を保証）
- **両環境対応**: ローカルとGitHub Actions両方で動作
GitHub Actions環境で`github-actions[bot]`アカウントが`gh api user`で認証エラーになる問題を解決
- 新しいissue作成によるワークフロー自動実行テスト
- GitHub Actions環境でのブランチ保護設定確認
- ローカル環境での動作確認（既存機能維持）
> Fix GitHub Actions authentication in setup-branch-protection.sh

- scripts/setup-branch-protection.sh
GitHub Actionsワークフローでsetup-branch-protection.shが終了コード1で失敗する問題を修正
- Issue #104で、ブランチ保護は正常に設定されたが、workflow の'Close completed issue'ステップがスキップされた
- PROTECTION_SUCCESS=falseになっていた原因は、grepコマンドのエラーハンドリング
- `grep -v`コマンドに`|| true`を追加（空ファイル対応）
- `grep -q`コマンドに`2>/dev/null`を追加（stderr抑制）
- bash strict mode(`set -e`)でのgrepエラーによる異常終了を防止
- ✅ ローカルでk18rs903の手動実行成功
- ✅ Issue #104が正常にクローズされた
- ✅ ブランチ保護設定が正常に動作
- 新しい学生リポジトリでの自動ワークフロー実行テスト
> Fix grep command error handling in GitHub Actions

- create-repo/main-wr.sh
- create-repo/main.sh
- scripts/setup-branch-protection.sh
- scripts/sync-students-from-repos.sh
- scripts/update-review-branch.sh
- scripts/update-student-registry.sh
このPRは、学籍番号形式として新たに `xxjkxxx` パターンのサポートを追加します。内部的な対応のため、ユーザー向けメッセージは従来通り `xxrsxxx` と `xxgjkxxx` 形式のみ表示します。
- **xxjkxxx 形式サポート**: `k##jk###` パターンの学籍番号に対応
- **卒業論文として処理**: xxjkxxx → sotsuron リポジトリ作成
- **シームレスな統合**: 既存機能に影響なし
**正規表現パターン更新**:
```regex
従来: ^k[0-9]{2}(rs[0-9]{3}|gjk[0-9]{2})$
更新: ^k[0-9]{2}(rs[0-9]{3}|jk[0-9]{3}|gjk[0-9]{2})$
```
**論文タイプ判定**:
- `k##rs###` → sotsuron（卒業論文）
- `k##jk###` → sotsuron（卒業論文）✨ NEW
- `k##gjk##` → thesis（修士論文）
1. **create-repo/main.sh** - メインのリポジトリ作成スクリプト
2. **create-repo/main-wr.sh** - 週報リポジトリ作成スクリプト  
3. **scripts/setup-branch-protection.sh** - ブランチ保護設定スクリプト
4. **scripts/update-review-branch.sh** - レビューブランチ更新スクリプト
5. **scripts/update-student-registry.sh** - 学生レジストリ更新スクリプト
**変更なし**: ユーザー向けメッセージは従来通り
```
学籍番号を入力してください
卒業論文の例: k21rs001
修士論文の例: k21gjk01
``` …
> Add support for xxjkxxx student ID format

- .github/workflows/student-repo-management.yml
- thesis-student-registryの更新時に学生ID抽出が正しく動作しない問題を修正
- completed-protection.txtから行全体ではなく学生IDのみを正しく抽出するように改善
- フォールバック機能と詳細ログを追加
ワークフローがthesis-student-registryを更新する際、latest_studentに以下の値が設定されていた：
```
k02jk059-sotsuron # Completed: 2025-06-24 Student: k02jk059
```
これにより、学生ID（k02jk059）ではなく行全体が抽出され、レジストリ更新が失敗していた。
- 正規表現を使用して"Student: k##xxx###"形式から学生IDを抽出
- リポジトリ名からの抽出をフォールバックとして追加
- デバッグ出力を追加して抽出過程を可視化
> Fix student ID extraction from completed-protection.txt

- scripts/process-pending-issues.sh
Issue処理スクリプトの `thesis-student-registry` 更新方式をローカルファイル操作からGitHub API直接更新に変更し、既存のGitHub Actionsワークフローと統一しました。
- **処理時間短縮**: 約1-3秒（従来2-5秒から改善）
- **ネットワーク効率**: API呼び出し1回（従来の複数git操作から改善）
- **即座の反映**: リモートリポジトリがリアルタイム更新
- **GitHub Actions整合**: 既存ワークフローと同じAPI使用方式
- **依存関係削減**: ローカルthesis-student-registryクローン不要
- **一貫性向上**: 全ての自動処理がGitHub API経由で統一
```bash
スクリプト → ローカルthesis-student-registry → git push → GitHub
```
```bash
スクリプト → GitHub Contents API → GitHub（即座に反映）
```
- `gh api repos/smkwlab/thesis-student-registry/contents/data/repositories.json`
- base64エンコーディングによるコンテンツ更新
- 適切なSHA取得とコミットメッセージ生成
- API アクセステスト事前実行
- JSON処理エラーの詳細検出
- リトライ機能との統合
- ドライランモード完全対応
- 既存ログ出力形式維持
- 統計レポート機能継続
- **GitHub API更新**: ✅ 成功（2秒で完了）
- **リモート反映**: ✅ 即座に https://github.com/smkwlab/thesis-student-registry/blob/main/d …
> Implement GitHub API direct update for thesis-student-registry

- scripts/process-pending-issues.sh
インタラクティブモードでのリポジトリ削除確認を簡略化
- `DELETE-PERMANENTLY`の入力要求を削除
- 複雑な最終確認プロセスを簡略化
✅ **「これはテスト用リポジトリですか？」確認**
✅ **リポジトリ名の再入力による確認**
```
1. 「これはテスト用リポジトリですか？」 [yes/NO]
↓ (yes)
2. 「リポジトリ名 'repo-name' を入力:」
↓ (名前が一致)
3. 削除実行
```
- **操作時間短縮**: 不必要な確認ステップを削除
- **使いやすさ向上**: より直感的な操作フロー
- **安全性維持**: 重要な確認は保持
- テスト用リポジトリのみ削除可能
- リポジトリ名の正確な入力が必要
- 誤操作防止機能は維持
この変更により、必要な安全対策を維持しながら、より効率的な削除操作が可能になります。
> Simplify repository deletion confirmation in interactive mode

- scripts/extract-student-info-from-issues.sh
- scripts/process-pending-issues.sh
軽微な改善提案（Issue #81）に基づく修正です。
- **エラーハンドリングの詳細化**: エラー時にファイル行数も表示
- **ファイル存在チェックの簡略化**: 冗長な`-e`チェックを削除  
- **エラー出力の改善**: `2>&1`でstderrをキャプチャ
Fixes #81
> Minor improvements to extract-student-info-from-issues.sh

- scripts/process-pending-issues.sh
- scripts/setup-branch-protection.sh
Issue #74で提案された管理者権限チェック機能の改善を実装しました。
- **関数名の改善**: `check_admin_permissions` → `verify_admin_permissions`（検証の意味合いをより明確に）
- **ドキュメント追加**: 関数の返り値を明記
- **ログ詳細化**: チェック対象リポジトリ名をログ出力
- **保守性向上**: コードの一貫性と可読性を改善
- 関数名がより適切に機能を表現
- デバッグ時の利便性向上
- 将来的な保守性の向上
Fixes #74
> Improve admin permission check function

- README.md
- create-repo/main.sh
- create-repo/setup.sh
- scripts/process-pending-issues.sh
Issue #166で提案された個人ユーザー対応を実装しました。組織外ユーザーが個人アカウント下でLaTeX環境を利用できるようになります。
- 組織メンバーシップ自動判定によるユーザータイプ検出
- 個人モードでのリポジトリ作成 (username/username-sotsuron)
- 管理機能（ブランチ保護・Registry・Issue作成）のスキップ
- README.mdに個人ユーザー向けセクションを追加
自動判定により組織外ユーザーは個人モードで動作します。
Resolves #166
> Add individual user support for setup.sh

- create-repo/main-latex.sh
setup-latex.shの実行時に以下のエラーが発生：
```
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
fatal: unable to auto-detect email address (got 'root@aa46b37c25f6.(none)')
```
main-latex.shにGitユーザー設定を追加：
```bash
git config user.email "setup-latex@smkwlab.github.io"
git config user.name "LaTeX Setup Tool"
```
既存のsetupスクリプト（main.sh、main-wr.sh、setup-ise.sh）と同じパターンに統一。
- Docker環境でのGitコミット時の身元不明エラーを解決
- セットアップツール用の適切な身元設定
- 既存パターンとの整合性確保
これにより、setup-latex.shが正常に動作するようになります。
> Fix Git user configuration in main-latex.sh

- create-repo/common-lib.sh
- scripts/process-pending-issues.sh
根本的な改善として、リポジトリタイプの判定をリポジトリ名ベースからIssue本文ベースに変更しました。これにより、`k02jk059-report59` のような複雑な命名パターンでも正確に処理できるようになります。
- `create_repository_issue` 関数で `repo_type` パラメータを `generate_issue_body` に渡すように修正
- Issue本文に「**リポジトリタイプ**: ${repo_type}」フィールドを追加
- 各 `main-*.sh` スクリプトから正確なタイプ情報が渡される
新しい判定優先順位：
1. **Issue本文からの直接抽出** - `リポジトリタイプ: latex` から確実に抽出
2. **Issue本文のキーワード判定** - 週報、情報科学演習、汎用LaTeX等のキーワード
3. **リポジトリ名パターン** - 従来のフォールバック機能として維持
4. **学生IDパターン** - 最後の手段
5. **未知パターンの latex 推定** - setup-latex.sh の汎用性を考慮
**Before**: `k02jk059-report59` → 判定不可 → Issue #199処理失敗
**After**: Issue本文の `リポジトリタイプ: latex` → 確実に latex 判定 → 正常処理
- ✅ Issue本文からの直接抽出が最優先で動作
- ✅ 既存のリポジトリ名パターン判定も維持（後方互換性）
- ✅ 複雑な命名パターンでも正確に判定
- ✅ 今後作成されるIssueは確実にタイプ情報を含む
1. **確実性**: 推測ベースから確実な情報ベースへ
2. **拡張性**: 新しいリポジトリタイプも簡単に対応可能
3. **保守性**: …
> Improve repository type detection by prioritizing Issue content over repository names

- create-repo/common-lib.sh
- create-repo/main-ise.sh
ISE リポジトリのセットアップが以下のエラーで失敗していました：
```
accepts at most 1 arg(s), received 11
❌ リポジトリの作成に失敗しました
```
ISE リポジトリのみが複雑な description を設定していたため、スペースで引数が分割されていました：
```bash
ISE_DESCRIPTION="Information Science Exercise Report #1 for k02jk059 - Pull Request Learning"
create_repository "..." "..." "private" "true"  # descriptionなし
```
当初は `common-lib.sh` の引数処理を配列ベースに修正しましたが、より根本的な解決策を採用しました：
```bash
ISE_DESCRIPTION="Information Science Exercise Report #$ISE_REPORT_NUM for $STUDENT_ID - Pull Request Learning"
create_repository "${ORGANIZATION}/${REPO_NAME}" "$TEMPLATE_REPOSITORY" "private" "true" "$ISE_DESCRIPTION"
create_repository "${ORGANIZATION}/${REPO_NAME}" "$TEMPLATE_REPOSITORY" "private" "true"
```
1. **一貫性**: 他の3つのリポジトリタイプ（thesis, wr, latex）と同じパターンに統一
2. **シンプル**: 不要な複雑性を排除
3. **実用性**: …
> Fix gh repo create argument handling to prevent ISE setup failures

- scripts/process-pending-issues.sh
- scripts/setup-branch-protection.sh
Issue 219, 220 が処理されない問題を修正します。
GitHub Actions workflow で `process-pending-issues.sh` が実行される際、`setup-branch-protection.sh` スクリプトが見つからないエラーが発生していました：
```
scripts/process-pending-issues.sh: line 1555: ./setup-branch-protection.sh: No such file or directory
```
1. 相対パス `./setup-branch-protection.sh` を `$SCRIPT_DIR/setup-branch-protection.sh` に変更
2. `setup-branch-protection.sh` にリポジトリ名を第2パラメータとして渡す機能を追加
3. ISEレポート処理時に正しいリポジトリ名を渡すように修正
4. 重複していた `setup_branch_protection_for_issue` 関数を削除し、外部スクリプトに統一
- ローカルでの動作確認済み
- この修正により workflow が正常に動作し、pending issues が処理されるようになります
> Fix branch protection script path issue in workflow

- create-repo/common-lib.sh
学籍番号入力時に無入力（Enterキーのみ）の場合、現在のGitHubユーザー名を自動的に使用する機能を追加しました。
`common-lib.sh` の `read_student_id` 関数を修正：
- 空入力を検出したら `gh api user --jq .login` でユーザー名取得
- ユーザーには何も表示せず、サイレントに処理
- 取得したユーザー名は通常通り検証・正規化される
- 開発者やテスターが素早く自分のアカウントでテスト可能
- 毎回学籍番号を入力する手間を省略
- 既存の動作には影響なし（明示的な入力は従来通り処理）
```bash
$ ./main-ise.sh
学籍番号を入力してください
例: k21rs001, k21gjk01
学籍番号: [Enter押下]
```
> Auto-use GitHub username when student ID input is empty

- scripts/bulk-setup-protection.sh
- scripts/setup-branch-protection.sh
Students with write access can check 'Merge without waiting for requirements to be met (bypass rules)' checkbox, allowing them to bypass branch protection.
Set `enforce_admins: true` in branch protection configuration.
- Modified `setup-branch-protection.sh`
- Modified `bulk-setup-protection.sh`
- Protection rules will be enforced for everyone, including admins
- Students cannot bypass review requirements
- Ensures proper review workflow is followed
This is a critical security fix to prevent accidental or intentional bypass of the review process.
> Fix: Enable enforce_admins to prevent students from bypassing protection rules

- create-repo/main-ise.sh
PR #246 の修正に重大な欠陥を発見しました。
**Problem with Previous Fix:**
```bash
git rm -rf .        # ← 全ファイル削除
> index.html        # ← 空ファイル作成
```
**Result:**
- initial ブランチ: `index.html` のみ
- review-branch: 全テンプレートファイル
- **PR #2 差分: README.md, sample-index.html, style.css など全ファイルが表示**
```bash
git rm index.html   # ← index.html のみ削除
> index.html        # ← 空ファイル作成
```
**Expected Result:**
- initial ブランチ: テンプレートファイル + 空の `index.html`
- review-branch: テンプレートファイル + 学生の `index.html`
- **PR #2 差分: index.html のみ表示（期待通り）**
- ❌ PR #2 に全テンプレートファイルが差分として表示
- ❌ review PR が無関係なファイルでクラッター
- ❌ 教員が学生のレポート内容に集中できない
- ✅ PR #2 に index.html のみが差分として表示
- ✅ クリーンで焦点の定まったレビュー
- ✅ 教員が学生のレポート内容に集中可能
**File Operations:**
- `git checkout --orphan initial` - 独立ブランチ作成
- `git rm index.html` - index.html のみ削除
- `> index.html` - …
> 🚨 URGENT FIX: Remove only index.html in initial branch creation

- create-repo/main-ise.sh
orphan ブランチ導入により review-branch から initial への PR 作成が失敗する問題を修正します。
PR #246-248 で initial ブランチを orphan ブランチに変更したことにより：
- review-branch（main から分岐）と initial（orphan）の間に共通履歴がない
- GitHub が共通履歴のないブランチ間での PR 作成を拒否
- エラー: `The review-branch branch has no history in common with initial`
review-branch を initial から分岐するよう変更：
1. orphan の initial ブランチ作成（空の index.html）
2. review-branch を initial から分岐
3. main ブランチの内容を review-branch にマージ
これにより：
- review-branch と initial に共通履歴が確保される
- GitHub で initial ← review-branch の PR 作成が可能
- 全行コメント可能性も維持される
- `main-ise.sh`: review-branch 作成順序を変更
- STEP 3: initial ブランチ作成（orphan）
- STEP 4: review-branch を initial から分岐し、main をマージ
- ise-report-template #42: update-review-branch.yml の一貫性確保
```bash
STUDENT_ID=k99rs999 /bin/bash -c "$(curl -fsSL …
```
> Fix #250: Make review-branch inherit from initial for PR creation

- create-repo/main-thesis.sh
main-thesis.sh に main-ise.sh で修正済みの orphan branch 対応を適用しました。
- `git checkout --orphan initial` で独立したブランチを作成
- LaTeX ファイルを除去し、`.tex_placeholder` ファイルを作成
- orphan branch として履歴を継承しない構造
- review-branch を initial から分岐するように変更
- main ブランチの内容を `--allow-unrelated-histories` でマージ
- エラーハンドリングを実装
main-ise.sh で実装済みの以下の修正を適用：
- Issue #250: review-branch を initial から分岐
- Issue #252: --allow-unrelated-histories フラグ追加
- Issue #235: initial branch の orphan 作成
- Issue #246: review-branch 作成の一貫性修正
**Before:**
```bash
git checkout -b review-branch
git push -u origin review-branch
```
**After:**
```bash
git checkout --orphan initial
git rm --cached --ignore-unmatch *.tex *.cls *.sty
echo '' > .tex_placeholder
git add .tex_placeholder
git commit -m "Setup initial branch..."
git push origin initial
git checkout …
```
> Apply orphan branch fixes from ISE template to thesis template

- create-repo/main-ise.sh
main-ise.sh のブランチ保護設定部分で発生していた `local: can only be used in a function` エラーを修正
- ISEレポートリポジトリ作成時に main-ise.sh:304行目でエラー発生
- `local` 宣言を関数外で使用していたため、bashスクリプトエラー
- セットアップが最終段階で失敗していた
- 304行目: `local protection_config_file=` → `protection_config_file=`
- 309行目: `local protection_config=` → `protection_config=`
- 関数外では `local` 宣言不要のため削除
- ✅ bash構文チェック成功
- ✅ 既存の関数内local宣言はそのまま維持
- ✅ スクリプトの機能に変更なし
- `create-repo/main-ise.sh`: local宣言2箇所を修正
今後のISEレポートリポジトリ作成でブランチ保護設定エラーが解消される
Resolves #270
> Fix local variable declaration error in main-ise.sh

- create-repo/main-thesis.sh
Fix 'local: can only be used in a function' error in main-thesis.sh during thesis repository setup.
During k19rs999-sotsuron repository creation, setup.sh failed with:
Lines 114 and 119 in main-thesis.sh were using 'local' keyword outside of function scope:
- Line 114:   
- Line 119: 
This is the same issue that was previously fixed in main-ise.sh.
Remove 'local' keywords from both variable declarations since they are used in main script scope, not function scope.
- Line 114:  → 
- Line 119:  → 
This fix aligns with the correction made in main-ise.sh and resolves the syntax error preventing thesis repository setup completion.
> Fix local variable declaration in main-thesis.sh

- create-repo/main-thesis.sh
main-thesis.shでのaldc関連ファイル削除処理を改善し、包括的なクリーンアップを実現します。
```bash
find . -name '*-aldc' -exec rm -rf {} + 2>/dev/null || true
```
- **改善前**: 特定パターンのファイルのみ削除
- **改善後**: すべての`*-aldc`パターンのファイル・ディレクトリを削除
- **安全性向上**: `find | xargs`から`find -exec`に変更
- **エラーハンドリング**: 失敗時のエラー抑制
aldcツールが生成する可能性のあるファイル・ディレクトリ：
- `README.md-aldc` - READMEバックアップ
- `.devcontainer-aldc/` - DevContainer設定バックアップ
- `main.tex-aldc` - LaTeXファイルバックアップ
- その他の`*-aldc`パターンのファイル
- **SC2038回避**: `find | xargs`の問題を解決
- **ファイル名対応**: 特殊文字を含むファイル名への対応
- **エラー処理**: 適切な失敗時処理
- ファイルが存在しない場合のエラー抑制
- 権限エラーの適切な処理
- スクリプト実行の継続性確保
前回PR #293のaldc削除処理をさらに包括的に改善するものです。
> Improve aldc file cleanup in main-thesis.sh

- scripts/process-pending-issues.sh
thesis-student-registry Issue #63の根本原因を修正しました。process-pending-issues.shでリポジトリ情報を登録する際に、Issue作成者のGitHub usernameを明示的に含めるようにしました。
`scripts/process-pending-issues.sh`の`update_thesis_student_registry`関数を修正：
- Issue作成者のGitHub usernameを`CURRENT_ISSUE_AUTHOR`から取得
- 新しいレジストリエントリに`github_username`フィールドを明示的に設定
- これにより、`registry-manager status -o`でOwner Activityが正しく表示されるようになります
- `update_thesis_student_registry`関数が`github_username`フィールドを含めていなかった
- そのため、`registry-manager status -o`でOwner ActivityがN/Aと表示されていた
- Issue作成者のGitHub usernameが`github_username`フィールドに保存される
- `registry-manager status -o`でOwner Activityが適切に表示される
- thesis-student-registry Issue #63: https://github.com/smkwlab/thesis-student-registry/issues/63
- 対応するthesis-student-registry PR: …
> Fix root cause of Issue #63: Include github_username in repository entries

- CLAUDE.md
- create-repo/main-latex.sh
- create-repo/setup.sh
- docs/CLAUDE-EXAMPLES.md
latex-templateを使用する際、学生以外のユーザー（教員、研究者、一般ユーザー）も利用できるよう、INDIVIDUAL_MODEで学籍番号の入力を不要にする機能を追加しました。
- `INDIVIDUAL_MODE=true`の場合、学籍番号の入力をスキップ
- リポジトリ名は単にドキュメント名のみ（例：`research-note`、`my-paper`）
- Registry Manager連携も学籍番号がある場合のみ実行
- `INDIVIDUAL_MODE=true`かつ`DOC_TYPE=latex`の場合、学籍番号を自動的に空に設定
- `CLAUDE.md`と`docs/CLAUDE-EXAMPLES.md`に新しい使用例を追加
```bash
INDIVIDUAL_MODE=true DOC_TYPE=latex DOCUMENT_NAME=my-paper /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/smkwlab/thesis-management-tools/main/create-repo/setup.sh)"
```
→ リポジトリ名：`my-paper`
```bash  
DOC_TYPE=latex STUDENT_ID=k21rs001 DOCUMENT_NAME=research-note /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/smkwlab/thesis-management-tools/main/create-repo/setup.sh)"
```
→ リポジトリ名：`k21rs001-research-note`
- …
> Enable flexible LaTeX repository creation in individual mode

- create-repo/setup.sh
Fixed Docker container hanging issue when using INDIVIDUAL_MODE with environment variables.
When running the setup script with all parameters provided via environment variables:
```bash
INDIVIDUAL_MODE=true DOC_TYPE=latex DOCUMENT_NAME=my-paper /bin/bash -c "$(curl -fsSL ...)"
```
The Docker container would hang because it was running with `-it` (interactive + TTY) options even though no user input was needed.
- Added logic to detect when interactive mode is not needed
- Use non-interactive mode when:
- `DOC_TYPE=latex`
- `INDIVIDUAL_MODE=true`
- `DOCUMENT_NAME` is provided via environment variable
- Keep interactive mode for all other cases where user input is expected
```bash
INDIVIDUAL_MODE=true DOC_TYPE=latex DOCUMENT_NAME=my-paper /bin/bash -c "$(curl -fsSL …
```
> Fix Docker interactive mode issue for INDIVIDUAL_MODE with DOCUMENT_NAME

- create-repo/common-lib.sh
- create-repo/main-latex.sh
- create-repo/setup.sh
INDIVIDUAL_MODEでのsetup.sh実行失敗を修正
INDIVIDUAL_MODEで実行時、`confirm_creation`関数の`read`コマンドで対話的入力を待機し、非対話的Dockerコンテナ内でハングしていました。
- INDIVIDUAL_MODE=trueの場合、確認プロンプトを自動承認
- 「個人モード: 自動的に続行します」メッセージを表示
- 対話的入力をスキップして処理を継続
```bash
INDIVIDUAL_MODE=true DOC_TYPE=latex /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/smkwlab/thesis-management-tools/main/create-repo/setup.sh)"
```
`confirm_creation`関数が組織モード向けに設計されていたため、個人モードでも対話的確認を要求していました。個人モードでは自動承認が適切です。
> Fix INDIVIDUAL_MODE confirmation issue in confirm_creation function
