smkwlab/thesis-management-tools

- scripts/create-student-repos.sh
Remove unnecessary comment and verbose template repo output for cleaner script execution.
> Minor cleanup: remove redundant comments and output

- create-repo/main.sh
- Simplify branch creation process by removing redundant git operations and improving logical flow
- Enhance GitHub authentication instructions with color-coded guidance for better user clarity
- Consolidate LaTeX environment setup into single commit after completion for cleaner git history
- Improve completion message formatting to make URLs easily copyable
- Replace detailed setup steps with direct link to WRITING-GUIDE.md for better documentation centralization
> Streamline repository setup workflow and improve user experience

- create-repo/main-wr.sh
- create-repo/setup-wr.sh
- Add setup-wr.sh: Entry point for wr-template repository creation
- Add main-wr.sh: Core logic for weekly report repository setup
- Support student ID format validation for weekly reports
- Simple main branch workflow (no complex branching like thesis)
- Integrate with aldc for LaTeX environment setup
- 📝 Add wr-template specific setup scripts
- 🔧 Docker-based approach consistent with thesis setup
- ✅ Student ID validation (k##rs### and other patterns)
- 🚀 One-liner setup command support
- 📚 Simple workflow suitable for weekly reports
- ✅ Tested with k19rs999 student account
- ✅ Successfully created repository: https://github.com/smkwlab/k19rs999-wr
- ✅ Verified Docker build and script execution
- ✅ Confirmed LaTeX environment integration
> Add weekly report repository setup scripts

- create-repo/main-wr.sh
- create-repo/setup-wr.sh
- Fix Docker command execution that was causing student ID parsing errors
- Change `bash main-wr.sh` to `./main-wr.sh` for direct script execution
> Fix Docker command execution in setup-wr.sh

- .claude/settings.local.json
- CLAUDE.md
- create-repo/setup-wr.sh
- create-repo/setup.sh
Docker build output was being suppressed in `setup.sh` and `setup-wr.sh` scripts using `2>/dev/null` redirection. This made it impossible for users to see build progress during long Docker builds, particularly when building with the texlive-ja-textlint base image.
Users reported confusion about whether the process was still running or had frozen, especially during the lengthy LaTeX environment setup.
```bash
if ! docker build -t thesis-setup-temp . 2>/dev/null; then
```
The `2>/dev/null` redirection suppressed all stderr output, which includes Docker's build progress information.
- Removed `2>/dev/null` redirection to allow build progress display
- Eliminated redundant error handling that would rebuild on failure
- **Normal mode**: `--progress=auto` shows appropriate build progress
- …
> Improve Docker build output visibility in setup scripts

- create-repo/main.sh
- scripts/setup-branch-protection.sh
- thesis-repo-manager.sh
Issue #38のレビュー結果 + 過去のPRレビューバックログに基づき、システムの安定性と運用性を大幅改善
1. **分のフォーマット統一** (High priority) - `printf "%02d:%02d"`に統一
2. **日付境界の処理実装** (Medium priority) - UTC 15:00以降の翌日処理対応
3. **未定義変数修正** - `$issue_title`を`$search_term`に修正
4. **GitHub API レート制限対応** - 大量学生処理時の安定性向上
- レート制限チェック機能
- API呼び出し間隔制御
- 対話的継続確認
5. **処理前バックアップ機能** - 重要ファイルの自動保護
6. **ロック機能強化** - より堅牢な並行実行制御
- タイムアウト機能（30秒）
- 古いロックファイル自動削除（5分以上）
- 一時ディレクトリ使用
```bash
```
- 学生リポジトリ作成: より安定な処理
- 大量処理: レート制限を考慮した安全な実行
- 並行実行: タイムアウトと回復機能付き
- Fixes #38 (JST timezone improvements)
- Addresses #35 (undefined variable)
- Partially addresses #23 (Phase 2.5 features)
- Partially addresses #28 (operational enhancements)
> Improve JST timezone handling based on PR #38 review

- scripts/setup-branch-protection.sh
> Fix GitHub CLI authentication and variable expansion issues

- create-repo/main.sh
Implement comprehensive label verification and automatic recovery system to prevent Issue #42-like problems where `branch-protection` label fails to be set during Issue creation.
**Discovered Problem**: Issue #42 was created without the required `branch-protection` label, causing setup-branch-protection.sh to fail finding it:
```bash
$ ./setup-branch-protection.sh k19rs990
[WARNING] ⚠️  関連Issueが見つかりませんでした（リポジトリ: smkwlab/k19rs990-sotsuron）
[WARNING]    手動でIssueをクローズしてください
```
**Root Cause**: 
- Label setting during `gh issue create` can fail due to permissions or API timing
- No verification or recovery mechanism existed
- setup-branch-protection.sh depends on `--label "branch-protection"` filter
```bash
🔍 ラベル設定を確認中...
sleep 2  # API reflection wait time
current_labels=$(gh issue view …
```
> Implement robust label verification and recovery for Issue creation

- create-repo/main.sh
- scripts/setup-branch-protection.sh
- Remove unnecessary backup functionality from branch protection setup
- Enhance Issue creation with automatic label verification
- Improve error handling and user guidance
- **Remove `create_backup()` function**: Eliminated redundant backup system from `setup-branch-protection.sh`
- **Simplify setup process**: Removed 31 lines of backup-related code
- **Git-based version control**: Files are already managed by Git, making separate backups redundant
- **Automatic label verification**: Prevent Issue #42-like problems where `branch-protection` label is missing
- **Label recovery system**: Automatically fix label issues when detected
- **Improved error messages**: Better guidance for GitHub CLI permission problems
- **Reduced complexity**: Simplified code maintenance and understanding
- …
> Clean up unnecessary functionality and improve Issue management

- CLAUDE.md
- create-repo/main-wr.sh
- create-repo/main.sh
- create-repo/setup-wr.sh
- create-repo/setup.sh
- scripts/setup-branch-protection.sh
- Add host GitHub CLI authentication check and token retrieval to replace container browser authentication
- Support multiple GitHub accounts with automatic detection and validation  
- Update both thesis (setup.sh) and weekly report (setup-wr.sh) workflows
- Fix branch protection script to work without label requirements from student accounts
- **Host-side validation**: Check GitHub CLI installation and authentication before container execution
- **Token extraction**: Securely retrieve authentication tokens from host and pass to containers
- **Multiple account support**: Detect and validate multiple GitHub accounts with conflict resolution
- **Improved UX**: Leverage host browser automation instead of manual container authentication
- **Secure token passing**: Use environment variables …
> Improve GitHub authentication flow for container-based repository creation

- create-repo/setup-wr.sh
- create-repo/setup.sh
- scripts/setup-branch-protection.sh
- test-issue-close.sh
- thesis-repo-manager.sh
Issue #35 のコードレビューで指摘された改善点を実装し、Issue自動クローズ機能を最適化。
- `DEBUG=1` でIssue検索の詳細情報を表示
- Issue未発見時のエラーメッセージを詳細化
- 権限不足/API制限時の警告を追加
- `check_rate_limit()` 関数で残りリクエスト数をチェック
- 10リクエスト未満で警告・処理中断
- リセット時刻も表示
- 既存のブランチ保護設定を事前確認
- 設定済みの場合はAPI呼び出しをスキップ
- それでも関連Issueは適切にクローズ
- まず`branch-protection`ラベル付きIssueを検索
- 見つからない場合はタイトルベース検索にフォールバック
- クローズ処理中のIssue番号をログ出力
- `scripts/setup-branch-protection.sh` と `thesis-repo-manager.sh` で同じ最適化を適用
- 統一されたエラーハンドリング
- コードの保守性向上
- Closes #35 
- Addresses code review feedback from PR #34
- より堅牢なIssue自動クローズ機能
- APIレート制限への対応
- デバッグ・トラブルシューティングの容易化
> Optimize Issue auto-close functionality (#35)

- .github/workflows/ai-reviewer.yml
AIレビューアーのスキーマ検証エラーを修正するため、修正版のai-reviewerを使用するように更新しました。
- `Nasubikun/ai-reviewer@v1` から `toshi0806/ai-reviewer@v1.1` に変更
- v1.1では、プロンプトとzodスキーマの不一致を修正済み
- PR #70でAIレビューコメントが投稿されなかった問題
- `NoObjectGeneratedError: Invalid enum value` エラー
- プロンプトで "PRIORITY:HIGH" を指定していたが、スキーマでは "HIGH" を期待していた不一致
- 新しいPRでAIレビューアーが正常に動作することを確認予定
> Fix AI reviewer schema validation error

- scripts/setup-branch-protection.sh
setup-branch-protection.shに管理者権限チェック機能を追加し、学生アカウントでの誤実行を防止
管理者が間違って学生アカウントをアクティブにしたまま`setup-branch-protection.sh`を実行すると、権限不足でブランチ保護設定に失敗する問題がありました。この場合、エラーメッセージが不明確で、原因の特定に時間がかかっていました。
1. **自動権限検証**
- GitHub APIを使用してsmkwlab/thesis-management-toolsリポジトリでのadmin権限を確認
- アカウント名のハードコーディングなしで汎用的に判定
2. **即座の実行拒否**
- 学生アカウントでの実行を権限チェック段階で完全にブロック
- 明確なエラーメッセージと具体的な解決策を表示
3. **シンプルな設計**
- 当初検討した--forceオプションを削除
- 安全性を優先したストレートな権限チェック
```bash
has_admin=$(gh api "repos/smkwlab/thesis-management-tools" --jq '.permissions.admin')
if [ "$has_admin" = "true" ]; then
else
fi
```
```
✅ 管理者権限を確認しました
→ 正常にブランチ保護設定実行
```
```
❌ 現在のアカウント（k18rs509）は管理者権限がありません
このアカウントではブランチ保護設定に失敗します
解決方法：
管理者アカウントに切り替えてから再実行してください
gh auth switch --user <admin-username>
```
1. **操作ミスの防止**: 管理者の誤ったアカウントでの実行を完全防止
2. **明確なエラー表示**: …
> Add admin permission check to setup-branch-protection.sh

- .github/workflows/student-repo-management.yml
• Replace 2-hour scheduled execution with immediate issue-based trigger
• Automatically process branch protection requests when issues are created
• Remove unnecessary scheduled runs
• Maintain manual trigger option for debugging
- ⚡ **Immediate processing**: No waiting up to 2 hours
- 🎯 **Event-driven**: Only runs when actually needed
- 🔧 **Efficient**: No unnecessary scheduled runs
- 🐛 **Debugging**: Manual trigger still available
- ❌ Remove: `schedule: cron: '0 */2 * * *'`
- ✅ Add: `issues: types: [opened]`
- ✅ Add: Conditional filter for branch protection issues
- ✅ Keep: `workflow_dispatch` for manual runs
**Before**: 
1. Student runs setup.sh → Issue created
2. Wait 0-2 hours for scheduled run
3. Data files finally updated
**After**:
1. Student runs setup.sh → Issue created
2. …
> Replace scheduled execution with automatic issue trigger

- .github/workflows/student-repo-management.yml
• Automatically setup branch protection immediately when issue is created
• Extract student ID from issue body and run setup-branch-protection.sh directly
• Eliminate manual teacher intervention requirement
• Complete end-to-end automation
🚀 **Full Automation**:
1. Student runs setup.sh → Issue created
2. Workflow triggers → Student info extracted + Branch protection setup
3. Issue automatically closed → Complete
⚡ **Immediate Processing**:
- No waiting for teacher action
- No manual setup-branch-protection.sh execution needed
- Repository ready for use within minutes
🎯 **Smart Processing**:
- Issue events: Direct setup for specific student
- Manual runs: Bulk processing for all pending
- Extract student ID using regex from issue body
- Run `./scripts/setup-branch-protection.sh …
> Add immediate branch protection setup on issue creation

- .github/workflows/student-repo-management.yml
- create-repo/main.sh
- docs/GITHUB-ACTIONS-SETUP.md
- scripts/setup-branch-protection.sh
GitHub Actionsでの完全自動化を実現するための修正
- ワークフローで`ORG_ADMIN_TOKEN`を優先使用、フォールバックで`GITHUB_TOKEN`
- 他のリポジトリ（学生のthesisリポジトリ）への"Repository not found"エラーを解決
- 管理者向け設定ガイドを追加 (docs/GITHUB-ACTIONS-SETUP.md)
- setup.sh実行時の"08: value too great for base"エラーを解決
- 朝の時間帯（08:xx, 09:xx）での実行エラーを修正
- `10#`プレフィックスで明示的に10進数として処理
- 設定手順の簡略化（必要な権限のみ記載）
- セキュリティ注意事項の追加
管理者は以下の設定が必要です：
1. Classic Personal Access Token作成（`repo`スコープのみ）
2. Repository Secretsに`ORG_ADMIN_TOKEN`として追加
詳細: docs/GITHUB-ACTIONS-SETUP.md
- ✅ Dockerコンテナ環境での8進数エラー再現・修正確認
- ✅ GitHub Actions認証フロー確認
- ✅ k18rs920での実際のエラー解決
- `ORG_ADMIN_TOKEN`設定後、新しい学生リポジトリでの自動ブランチ保護設定テスト
- 朝の時間帯でのsetup.sh実行テスト
> Fix GitHub Actions authentication and octal number issues

- scripts/setup-branch-protection.sh
Issue #106で発生したGitHub Actions失敗の根本原因を修正
- `setup-branch-protection.sh`の行320: `((success_count++))`
- `bash strict mode`(`set -e`)でエラーが発生し、スクリプトが異常終了
- `review-branch`保護設定中にスクリプトが途中で止まる
- 結果として`PROTECTION_SUCCESS=false`になり、Issue自動クローズがスキップ
- `((success_count++))` → `success_count=$((success_count + 1))`
- bash strict mode対応の徹底
- API呼び出し時の詳細エラー出力
- 失敗時の終了コードとエラーメッセージ表示
- デバッグ情報の充実
- ✅ PR #105でgrepエラーは修正済み
- ✅ ローカルでk18rs904の手動実行は成功
- ✅ Issue #106が手動実行で正常にクローズ
- ✅ ブランチ保護設定は実際に動作
次回のGitHub Actions実行時：
- ✅ `PROTECTION_SUCCESS=true`で正常完了
- ✅ Issue自動クローズの実行
- ✅ 完全自動化フローの実現
新しい学生リポジトリでの自動ワークフロー実行テスト
> Fix remaining arithmetic operation errors causing GitHub Actions failures

- .github/workflows/student-repo-management.yml
リポジトリチェックが失敗する原因を特定するためのデバッグ出力を追加
> Add debug output for repository checking

- create-repo/Dockerfile
- create-repo/Dockerfile-wr
- scripts/process-pending-issues.sh
Issue #133のレビュー提案を実装してAlpine版Dockerコンテナを改善
**効果**:
- texlive-ja-textlintと同じAlpineバージョンで統一
- 予期しないアップストリーム変更から保護
- セキュリティとビルド安定性の向上
**効果**:
- APIレスポンス形式変更に対する耐性向上
- JSONパースエラーの削減
- より信頼性の高いビルドプロセス
- **texlive-ja-textlint**: alpine:3.22.0
- **thesis-management-tools**: alpine:3.22.0 ← 今回統一
- ✅  (論文リポジトリ作成用)
- ✅  (週報リポジトリ作成用)
1. **予測可能性**: ビルド結果の一貫性
2. **セキュリティ**: 検証済みバージョンの使用
3. **デバッグ容易性**: 問題の再現が容易
1. **エラー耐性**: パース失敗の削減
2. **保守性**: 理解しやすいコード
3. **拡張性**: 追加のJSON処理が容易
- Resolves #133 - Alpine版Dockerコンテナ実装のレビュー結果と改善提案
この変更により、Issue #133で提案された改善項目を完全に実装し、エコシステム全体でのAlpine版統一とセキュリティ向上を実現します。
> Implement Alpine Docker improvements from Issue #133

- scripts/process-pending-issues.sh
- scripts/setup-branch-protection.sh
Issue #76で指摘された学生リスト管理の改善を実装しました。
- **区切り文字の変更**: `#` から `|` に変更し、解析問題を解決
- **フォーマット改善**: `repo_name|Completed: date|Student: student_id`
- **対象ファイル**: 
- `scripts/setup-branch-protection.sh`
- `scripts/process-pending-issues.sh`
- リポジトリ名に `#` 文字が含まれる場合の解析エラーを防止
- 将来的なスクリプトでの解析の確実性向上
- 保守性とスケーラビリティの改善
Fixes #76
> Improve student list management format and duplicate detection

- .gitignore
- CLAUDE.md
- create-repo/main.sh
- data/.gitkeep
- scripts/extract-student-info-from-issues.sh
- scripts/process-pending-issues.sh
- scripts/setup-branch-protection.sh
データ管理を thesis-student-registry リポジトリに統合し、単一の真実のソースを確立
- thesis-management-tools/data ディレクトリを完全削除
- 全スクリプトを GitHub API 経由での統合管理に移行
- ローカルファイル依存を排除し、保守性とスケーラビリティを向上
- **統合前**: 分散した複数のテキストファイル管理
- **統合後**: thesis-student-registry/data/repositories.json での統一管理
- \`setup-branch-protection.sh\`: ローカルファイル操作を削除、統合管理ワークフローに移行
- \`process-pending-issues.sh\`: data/ ディレクトリ参照を削除、GitHub API 管理に変更
- \`extract-student-info-from-issues.sh\`: ローカルファイル管理機能を削除
- \`main.sh\`: 保護設定確認を repositories.json 参照に変更
\`\`\`diff
- data/
-   ├── protection-status/
-   │   ├── pending-protection.txt
-   │   └── completed-protection.txt
-   └── repositories/
-       └── active.txt
+ # All data now managed in thesis-student-registry/data/repositories.json
\`\`\`
- CLAUDE.md を統合後のワークフローに更新
- 新しい管理コマンドの使用例を追加
- データ管理統合の説明を追加 …
> Consolidate student data management to thesis-student-registry

- create-repo/Dockerfile-ise
- create-repo/main-ise.sh
- create-repo/setup-ise.sh
- create-repo/setup-universal.sh
- create-repo/setup-wr.sh
- Add unified setup script supporting all document types (thesis, wr, latex, ise)
- Reduce 95% code duplication across setup*.sh scripts
- Support explicit document type specification via DOC_TYPE environment variable
- Maintain compatibility with existing Docker-based architecture
- **Document Type Support**: thesis, wr, latex, ise
- **Simple Usage**: `DOC_TYPE=thesis ./setup-universal.sh`
- **Code Deduplication**: Consolidates common authentication, user detection, and Docker execution logic
- **ISE Special Handling**: Non-Docker execution for ISE document type
- **Error Handling**: Clear error messages for invalid or missing document types
\`\`\`bash
DOC_TYPE=thesis ./setup-universal.sh
DOC_TYPE=wr ./setup-universal.sh
DOC_TYPE=latex ./setup-universal.sh
DOC_TYPE=ise …
> Implement setup-universal.sh to reduce code duplication

- .github/workflows/ai-reviewer.yml
- create-repo/common-lib.sh
- create-repo/main-ise.sh
- create-repo/main-latex.sh
- create-repo/main-thesis.sh
- create-repo/main-wr.sh
- create-repo/setup.sh
This PR significantly improves the user experience by cleaning up verbose and unnecessary output from the setup scripts. The changes focus on keeping only essential information visible to students while maintaining all functionality.
**Removed Verbose Git Output**:
- Suppress `git add`, `git commit`, `git checkout`, and `git push` command output
- Hide detailed Git operation messages like commit hashes and remote responses
- Redirect Git commands to `/dev/null` to maintain clean output
**Simplified Success Messages**:
- Remove confusing usage examples from setup completion message
- Keep only essential "✅ セットアップが完了しました！" message
- Remove redundant file documentation references
**Branch Protection Streamlining**:
- Simplify to single "ブランチ保護設定中..." message
- Remove verbose issue creation …
> Clean up script output for better user experience

- create-repo/README.md
- Complete truncated URL in troubleshooting section
- Add blank line before debug mode code block for better formatting
- Improve documentation readability and accuracy
> Fix documentation: complete truncated URL and improve formatting

- create-repo/common-lib.sh
- create-repo/main-ise.sh
- create-repo/main-latex.sh
- scripts/process-pending-issues.sh
- Add comprehensive support for ISE (Information Science Exercise) and LaTeX (general-purpose) repository types
- Complete system modernization by removing legacy data structures
- Implement proper error handling for registry registration
- Enhance user experience with improved messaging
- **Purpose**: Pull Request learning for students
- **Processing**: Branch protection + registry registration + Issue closure
- **Educational goal**: Learn collaborative development workflow
- **Purpose**: Flexible LaTeX document creation (research notes, reports, etc.)
- **Processing**: Registry registration + Issue closure (no branch protection for flexibility)
- **User experience**: Direct main branch work for rapid iteration
- **Fixed misleading messages**: "ブランチ保護設定中..." → "Registry Manager登録中..."
- …
> Add ISE and LaTeX repository types support + system modernization

- create-repo/main-thesis.sh
- Simplify thesis type determination logic to use single character check
- Update repository naming convention for graduate students
- Fix classification issues with complex pattern matching
- Graduate students (k##g*): classified as \`shuuron\` → repository name: \`studentid-master\`
- All other students: classified as \`sotsuron\` → repository name: \`studentid-sotsuron\`
- Remove complex regex patterns that were causing misclassification
> Simplify thesis type determination and update repository naming

- create-repo/main-ise.sh
k19rs999 アカウントでの実際のリポジトリ作成テストで発見：
- main-ise.sh が `git rm index.html` の段階で失敗
- 「📝 initial ブランチを作成中...」で停止
- スクリプト実行が完了しない
**Orphan Branch Staging Behavior:**
```bash
git checkout --orphan initial  # ← 全ファイルがステージング状態
git rm index.html              # ← エラー: ファイルがstaged状態
```
**Error Message:**
```
error: the following file has changes staged in the index:
index.html
(use --cached to keep the file, or -f to force removal)
```
```bash
git rm index.html >/dev/null 2>&1
git rm --cached index.html >/dev/null 2>&1
```
**Manual Completion of k19rs999-ise-report1:**
- ✅ `git rm --cached index.html` - 成功
- ✅ `> index.html` - 空ファイル作成
- ✅ `git commit` - initial ブランチ完成
- ✅ `git push origin initial` - リモート反映
**Final Repository State:**
- ✅ main: セットアップ済み
- ✅ review-branch: セットアップ済み  
- ✅ initial: 空の …
> Fix orphan branch git rm command in main-ise.sh

- create-repo/Dockerfile-ise
- create-repo/Dockerfile-thesis
- create-repo/main-ise.sh
- create-repo/main-thesis.sh
- create-repo/protection-config.json
学生リポジトリの review-branch に対するブランチ保護を自動設定する機能を実装しました。
- `create-repo/main-ise.sh`: ISEレポート作成時にreview-branch保護を追加
- `create-repo/main-thesis.sh`: 卒論/修論リポジトリ作成時にreview-branch保護を追加
- **直接プッシュの禁止**: 学生による誤った直接変更を防止
- **GitHub Actions例外**: 自動更新ワークフローのみ許可（`restrictions.apps: ["github-actions"]`）
- **フォースプッシュ禁止**: ブランチ履歴の保護
- **ブランチ削除禁止**: 誤削除の防止
- **管理者制限なし**: 緊急時の教員による修正は可能
- 添削用PRの整合性維持
- 学生の誤操作によるトラブル防止
- PR-based reviewシステムの信頼性向上
- 組織リポジトリでのみ適用（個人リポジトリはスキップ）
- API エラー時は警告メッセージを表示し、処理を継続
Resolves #259
> Add review-branch protection to prevent accidental student modifications

- create-repo/common-lib.sh
- create-repo/main-ise.sh
- create-repo/main-thesis.sh
main-ise.sh と main-thesis.sh で重複していた orphan branch 関連処理を common-lib.sh に共通化しました。
1. **create_orphan_initial_branch()** - initial ブランチ（orphan）の作成
- プレースホルダーファイル作成
- 不要ファイル削除
- orphan ブランチコミット・プッシュ
2. **create_review_branch_from_initial()** - review-branch の作成
- initial から分岐
- main ブランチとのマージ（--allow-unrelated-histories）
- エラーハンドリング
3. **setup_orphan_branch_workflow()** - ワークフロー全体のラッパー関数
- 上記2つの関数を連続実行
- 指定ブランチへの自動復帰
- 統一されたエラーハンドリング
- **main-ise.sh**: 35行の処理を1行の関数呼び出しに簡素化
- **main-thesis.sh**: 43行の処理を1行の関数呼び出しに簡素化
```bash
echo "📝 initial ブランチを作成中..."
git checkout --orphan initial >/dev/null 2>&1
setup_orphan_branch_workflow "index.html" "index.html" "ISE report" "0th-draft" || exit 1
```
- **78行の重複コード**を共通関数に集約
- 同一ロジックの複数実装を削除
- 修正時は common-lib.sh の1箇所のみ更新
- 両スクリプトに自動的に反映
- …
> Refactor orphan branch logic into common-lib.sh for DRY principle

- create-repo/common-lib.sh
- create-repo/main-ise.sh
- create-repo/main-thesis.sh
Fixes two critical issues preventing proper thesis repository setup: missing 0th-draft branch creation and protection-config.json file not found. 
Resolves #283
> Fix 0th-draft branch creation and protection-config.json path issues
